import React from "react";

function Footer() {
  return (
    <div className="footer">
      DISCLAIMER: OurBabyAI is an AI baby generator that creates images of a
      future child from parent photos. While we strive to ensure accuracy,
      please keep in mind that the images are generated by an AI model, which
      may result in some discrepancies from the actual child's appearance. Our
      service is for entertainment only and should not be utilized for medical
      or genetic information.
    </div>
  );
}

export default Footer;
